name: My First Workflow

on: [push, fork]

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

    - name: Welcome message
      run: echo "My First GitHub Action Job"
    
    - name: List files
      run: ls

    - name: Read file
      run: cat README.md

