name: Workflow Filters and Activities

on:
    workflow_dispatch:
    push:
        branches:
            - main
            - '!feature/*'   # ignoring pushing to any branch name starting with feature using !
    
    pull_request:
        types:            # workflow will run when a pull request is opened or closed
            - opened          
            - closed
        paths-ignore:    # workflow will only run when a pull request that includes a change on any file other than README.md
            - README.md
        branches:        # configure your workflow to only run on pull request that target specific branches
            - main

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
        - run: echo this workflow/job/step is executed for event type - ${{github.event_name}}